import './globals.css';
import { Inter } from 'next/font/google';

import Topbar from '@/components/Topbar';
import Provider from './Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Auth in Next JS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <Provider>
          <Topbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
